import type { Committee } from "../interfaces/Committee";

export const committees: Committee[] = [
  {
    name: "Tribunal de Distrito de los Estados Unidos para el Distrito Sur de Nueva York",
    topic: "Caso de Sean Combs (P. Diddy)",
    img: "/public/2.png",
    color: "purple-900",
    seats: 20,
    seatsList: [
      { name: "Estados Unidos", available: false },
      { name: "Reino Unido", available: false },
      { name: "Francia", available: true },
      { name: "Rusia", available: true },
      { name: "China", available: true },
      { name: "Alemania", available: true },
      { name: "Japón", available: true },
      { name: "India", available: true },
      { name: "Brasil", available: true },
      { name: "Canadá", available: false },
      { name: "Australia", available: true },
      { name: "Italia", available: true },
      { name: "España", available: true },
      { name: "México", available: true },
      { name: "Sudáfrica", available: true },
      { name: "Turquía", available: true },
      { name: "Corea del Sur", available: true },
      { name: "Argentina", available: true },
      { name: "Colombia", available: true },
      { name: "Egipto", available: true },
    ],
    description:
      "El Tribunal de Distrito de los Estados Unidos para el Distrito Sur de Nueva York es una corte federal que tiene jurisdicción sobre casos penales y civiles en el distrito sur del estado de Nueva York. Este tribunal es conocido por manejar casos de alto perfil, incluyendo delitos financieros, crimen organizado y casos relacionados con el terrorismo. En este comité, los delegados asumirán el papel de jueces, abogados y fiscales en el caso de Sean Combs, también conocido como P. Diddy, quien fue acusado en 1999 de varios cargos relacionados con un tiroteo en un club nocturno de Nueva York. Los delegados deberán analizar las pruebas presentadas, escuchar los argumentos de ambas partes y emitir un veredicto basado en la ley y los hechos del caso.",
    studyGuide: "https://www.nysd.uscourts.gov/",
    legalFramework: [
      "https://es.wikipedia.org/wiki/Sean_Combs#Incidentes_legales",
      "https://www.nytimes.com/2001/05/25/nyregion/diddy-is-acquitted-in-shooting-at-club.html",
    ],
  },
  {
    name: "Asamblea General",
    topic: "Genocidio de Camboya (1979)",
    img: "/public/ag.png",
    color: "red-900",
    seats: 193,
    seatsList: [
      { name: "Estados Unidos", available: true },
      { name: "Reino Unido", available: true },
      { name: "Francia", available: true },
      { name: "Rusia", available: true },
      { name: "China", available: true },
      { name: "Alemania", available: true },
      { name: "Japón", available: true },
      { name: "India", available: true },
      { name: "Brasil", available: true },
      { name: "Canadá", available: true },
      { name: "Australia", available: true },
      { name: "Italia", available: true },
      { name: "España", available: true },
      { name: "México", available: true },
      { name: "Sudáfrica", available: true },
      { name: "Turquía", available: true },
      { name: "Corea del Sur", available: true },
      { name: "Argentina", available: true },
      { name: "Colombia", available: true },
      { name: "Egipto", available: true },
    ],
    description:
      "La Asamblea General de las Naciones Unidas es uno de los seis órganos principales de la ONU y está compuesta por todos los estados miembros. Cada estado tiene un voto, independientemente de su tamaño o poder económico. La Asamblea General se reúne anualmente para discutir y coordinar políticas internacionales en una amplia gama de temas, incluyendo la paz y la seguridad, el desarrollo económico y social, los derechos humanos y el derecho internacional. En este comité, los delegados representarán a sus respectivos países y debatirán sobre el genocidio de Camboya, que ocurrió entre 1975 y 1979 bajo el régimen de los Jemeres Rojos. Los delegados deberán analizar las causas y consecuencias del genocidio, así como proponer medidas para prevenir futuros actos de genocidio y promover la justicia y la reconciliación en Camboya.",
    studyGuide: "https://www.un.org/en/ga/",
    legalFramework: [
      "https://es.wikipedia.org/wiki/Genocidio_camboyano",
      "https://www.un.org/en/genocideprevention/cambodia.shtml",
    ],
  },
  {
    name: "Cabinet of the United Kingdom",
    topic: "London Bombing (2005)",
    img: "/public/3.png",
    color: "gray-900",
    seats: 20,
    seatsList: [
      { name: "Estados Unidos", available: true },
      { name: "Reino Unido", available: true },
      { name: "Francia", available: true },
      { name: "Rusia", available: true },
      { name: "China", available: true },
      { name: "Alemania", available: true },
      { name: "Japón", available: true },
      { name: "India", available: true },
      { name: "Brasil", available: true },
      { name: "Canadá", available: true },
      { name: "Australia", available: true },
      { name: "Italia", available: true },
      { name: "España", available: true },
      { name: "México", available: true },
      { name: "Sudáfrica", available: true },
      { name: "Turquía", available: true },
      { name: "Corea del Sur", available: true },
      { name: "Argentina", available: true },
      { name: "Colombia", available: true },
      { name: "Egipto", available: true },
    ],
    description:
      "El Gabinete del Reino Unido es el principal órgano de toma de decisiones del gobierno británico y está compuesto por los ministros más importantes, incluyendo al Primer Ministro y a los jefes de los departamentos gubernamentales. El Gabinete se reúne regularmente para discutir y coordinar políticas en una amplia gama de temas, incluyendo la economía, la seguridad nacional, la salud y la educación. En este comité, los delegados asumirán el papel de miembros del Gabinete y debatirán sobre los atentados de Londres que ocurrieron el 7 de julio de 2005. Estos ataques terroristas coordinados tuvieron como objetivo el sistema de transporte público de Londres y resultaron en la muerte de 52 personas y cientos de heridos. Los delegados deberán analizar las causas y consecuencias de los atentados, así como proponer medidas para mejorar la seguridad nacional y prevenir futuros actos de terrorismo en el Reino Unido.",
  },
  {
    name: "Consejo de Seguridad",
    topic: "Tercera Guerra Mundial (2050)",
    img: "/public/4.png",
    color: "yellow-900",
    seats: 15,
    seatsList: [
      { name: "Estados Unidos", available: true },
      { name: "Reino Unido", available: true },
      { name: "Francia", available: true },
      { name: "Rusia", available: true },
      { name: "China", available: true },
      { name: "Alemania", available: true },
      { name: "Japón", available: true },
      { name: "India", available: true },
      { name: "Brasil", available: true },
      { name: "Canadá", available: true },
      { name: "Australia", available: true },
      { name: "Italia", available: true },
      { name: "España", available: true },
      { name: "México", available: true },
      { name: "Sudáfrica", available: true },
      { name: "Turquía", available: true },
      { name: "Corea del Sur", available: true },
      { name: "Argentina", available: true },
      { name: "Colombia", available: true },
      { name: "Egipto", available: true },
    ],
    description:
      "El Consejo de Seguridad de las Naciones Unidas es uno de los seis órganos principales de la ONU y es responsable de mantener la paz y la seguridad internacionales. Está compuesto por 15 miembros, incluyendo cinco miembros permanentes con derecho a veto (Estados Unidos, Rusia, China, Francia y el Reino Unido) y diez miembros no permanentes elegidos por la Asamblea General por un período de dos años. El Consejo de Seguridad tiene la autoridad para tomar decisiones vinculantes sobre cuestiones relacionadas con la paz y la seguridad, incluyendo la imposición de sanciones, el establecimiento de misiones de mantenimiento de la paz y la autorización del uso de la fuerza militar. En este comité, los delegados representarán a sus respectivos países y debatirán sobre un escenario ficticio de una Tercera Guerra Mundial en el año 2050. Los delegados deberán analizar las causas y consecuencias del conflicto, así como proponer medidas para resolver la crisis y promover la paz y la seguridad internacionales.",
  },
  {
    name: "Cumbre para la reestructuración política global",
    topic: "Nuevo Orden Mundial (2050)",
    img: "/public/5.png",
    color: "gray-900",
    seats: 50,
    seatsList: [
      { name: "Estados Unidos", available: true },
      { name: "Reino Unido", available: true },
      { name: "Francia", available: true },
      { name: "Rusia", available: true },
      { name: "China", available: true },
      { name: "Alemania", available: true },
      { name: "Japón", available: true },
      { name: "India", available: true },
      { name: "Brasil", available: true },
      { name: "Canadá", available: true },
      { name: "Australia", available: true },
      { name: "Italia", available: true },
      { name: "España", available: true },
      { name: "México", available: true },
      { name: "Sudáfrica", available: true },
      { name: "Turquía", available: true },
      { name: "Corea del Sur", available: true },
      { name: "Argentina", available: true },
      { name: "Colombia", available: true },
      { name: "Egipto", available: true },
    ],
  },
  {
    name: "Organización Mundial de la Salud",
    topic: "Rebrote de la Peste Negra (2050)",
    img: "/public/6.png",
    color: "green-900",
    seats: 194,
    seatsList: [
      { name: "Estados Unidos", available: true },
      { name: "Reino Unido", available: true },
      { name: "Francia", available: true },
      { name: "Rusia", available: true },
      { name: "China", available: true },
      { name: "Alemania", available: true },
      { name: "Japón", available: true },
      { name: "India", available: true },
      { name: "Brasil", available: true },
      { name: "Canadá", available: true },
      { name: "Australia", available: true },
      { name: "Italia", available: true },
      { name: "España", available: true },
      { name: "México", available: true },
      { name: "Sudáfrica", available: true },
      { name: "Turquía", available: true },
      { name: "Corea del Sur", available: true },
      { name: "Argentina", available: true },
      { name: "Colombia", available: true },
      { name: "Egipto", available: true },
    ],
  },
  {
    name: "Laboratorio Nacional de Los Álamos",
    topic: "Proyecto Manhattan",
    img: "/public/7.png",
    color: "orange-900",
    seats: 10,
    seatsList: [
      { name: "Estados Unidos", available: true },
      { name: "Reino Unido", available: true },
      { name: "Francia", available: true },
      { name: "Rusia", available: true },
      { name: "China", available: true },
      { name: "Alemania", available: true },
      { name: "Japón", available: true },
      { name: "India", available: true },
      { name: "Brasil", available: true },
      { name: "Canadá", available: true },
      { name: "Australia", available: true },
      { name: "Italia", available: true },
      { name: "España", available: true },
      { name: "México", available: true },
      { name: "Sudáfrica", available: true },
      { name: "Turquía", available: true },
      { name: "Corea del Sur", available: true },
      { name: "Argentina", available: true },
      { name: "Colombia", available: true },
      { name: "Egipto", available: true },
    ],
  },
];
